import type { AssessmentQuestion } from '@/types/assessment.types';

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'grammar-articles-1',
    category: 'grammar',
    topic: 'Articles',
    question: 'I saw ___ interesting movie yesterday.',
    options: ['a', 'an', 'the', '—'],
    correctAnswer: 'an',
  },
  {
    id: 'grammar-present-perfect-1',
    category: 'grammar',
    topic: 'Present Perfect',
    question: 'She ___ in London since 2022.',
    options: ['lives', 'lived', 'has lived', 'is living'],
    correctAnswer: 'has lived',
  },
  {
    id: 'grammar-prepositions-1',
    category: 'grammar',
    topic: 'Prepositions',
    question: 'I am interested ___ learning Spanish.',
    options: ['at', 'in', 'on', 'for'],
    correctAnswer: 'in',
  },
  {
    id: 'grammar-conditionals-1',
    category: 'grammar',
    topic: 'Conditionals',
    question: 'If I had more time, I ___ another language.',
    options: ['learn', 'will learn', 'would learn', 'learned'],
    correctAnswer: 'would learn',
  },
  {
    id: 'grammar-past-perfect-1',
    category: 'grammar',
    topic: 'Past Perfect',
    question: 'When we arrived, the movie ___.',
    options: ['already started', 'had already started', 'has already started', 'starts'],
    correctAnswer: 'had already started',
  },
  {
    id: 'grammar-modal-verbs-1',
    category: 'grammar',
    topic: 'Modal Verbs',
    question: 'You ___ see a doctor if you feel worse.',
    options: ['should', 'would', 'might to', 'must to'],
    correctAnswer: 'should',
  },
  {
    id: 'grammar-relative-clauses-1',
    category: 'grammar',
    topic: 'Relative Clauses',
    question: 'The woman ___ lives next door is a doctor.',
    options: ['which', 'whose', 'who', 'where'],
    correctAnswer: 'who',
  },
  {
    id: 'grammar-gerunds-1',
    category: 'grammar',
    topic: 'Gerunds and Infinitives',
    question: 'I enjoy ___ English in the evening.',
    options: ['study', 'to study', 'studying', 'studied'],
    correctAnswer: 'studying',
  },
  {
    id: 'grammar-passive-1',
    category: 'grammar',
    topic: 'Passive Voice',
    question: 'The project ___ last week.',
    options: ['completed', 'was completed', 'has completed', 'completes'],
    correctAnswer: 'was completed',
  },
  {
    id: 'grammar-reported-speech-1',
    category: 'grammar',
    topic: 'Reported Speech',
    question: 'She said that she ___ tired.',
    options: ['is', 'was', 'has been', 'will be'],
    correctAnswer: 'was',
  },

  {
    id: 'vocabulary-phrasal-verbs-1',
    category: 'vocabulary',
    topic: 'Phrasal Verbs',
    question: 'What does "give up" mean?',
    options: ['continue', 'quit', 'start', 'remember'],
    correctAnswer: 'quit',
  },
  {
    id: 'vocabulary-work-1',
    category: 'vocabulary',
    topic: 'Work',
    question: 'Someone who writes software is a ___.',
    options: ['developer', 'publisher', 'journalist', 'designer'],
    correctAnswer: 'developer',
  },
  {
    id: 'vocabulary-travel-1',
    category: 'vocabulary',
    topic: 'Travel',
    question: 'Where do you go to get on a plane?',
    options: ['platform', 'gate', 'aisle', 'counter'],
    correctAnswer: 'gate',
  },
  {
    id: 'vocabulary-emotions-1',
    category: 'vocabulary',
    topic: 'Emotions',
    question: 'If someone is "relieved", they feel ___ after a stressful situation.',
    options: ['calmer', 'angrier', 'more confused', 'more disappointed'],
    correctAnswer: 'calmer',
  },
  {
    id: 'vocabulary-education-1',
    category: 'vocabulary',
    topic: 'Education',
    question: 'A person who is studying at a university is a ___.',
    options: ['student', 'professor', 'principal', 'research'],
    correctAnswer: 'student',
  },
  {
    id: 'vocabulary-idioms-1',
    category: 'vocabulary',
    topic: 'Idioms',
    question: 'If something is "a piece of cake", it is ___.',
    options: ['expensive', 'easy', 'boring', 'dangerous'],
    correctAnswer: 'easy',
  },
  {
    id: 'vocabulary-technology-1',
    category: 'vocabulary',
    topic: 'Technology',
    question: 'What does "debug" mean?',
    options: [
      'write documentation',
      'find and fix errors',
      'delete a project',
      'install software',
    ],
    correctAnswer: 'find and fix errors',
  },
  {
    id: 'vocabulary-personality-1',
    category: 'vocabulary',
    topic: 'Personality',
    question: 'Someone who is "reliable" can be ___.',
    options: ['trusted', 'ignored', 'avoided', 'surprised'],
    correctAnswer: 'trusted',
  },
  {
    id: 'vocabulary-formal-1',
    category: 'vocabulary',
    topic: 'Formal English',
    question: 'Which word is more formal than "help"?',
    options: ['assist', 'fix', 'join', 'bring'],
    correctAnswer: 'assist',
  },
  {
    id: 'vocabulary-context-1',
    category: 'vocabulary',
    topic: 'Context',
    question: 'The instructions were very ___, so everyone understood what to do.',
    options: ['vague', 'clear', 'random', 'rare'],
    correctAnswer: 'clear',
  },
];